// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

func (p *PanelDef) ShouldComponentUpdateIntf(nextProps, prevState, nextState interface{}) bool {
	res := false

	{
		res = p.Props() != nextProps.(PanelProps) || res
	}
	return res
}

// Props is an auto-generated proxy to the current props of Panel
func (p *PanelDef) Props() PanelProps {
	uprops := p.ComponentDef.Props()
	return uprops.(PanelProps)
}

func (p PanelProps) EqualsIntf(val interface{}) bool {
	return p == val.(PanelProps)
}

var _ react.Equals = PanelProps{}
