// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type PreviewElem struct {
	react.Element
}

func (p PreviewDef) ShouldComponentUpdateIntf(nextProps, prevState, nextState interface{}) bool {
	res := false

	{
		res = p.Props() != nextProps.(PreviewProps) || res
	}
	return res
}

func buildPreview(cd react.ComponentDef) react.Component {
	return PreviewDef{ComponentDef: cd}
}

// Props is an auto-generated proxy to the current props of Preview
func (p PreviewDef) Props() PreviewProps {
	uprops := p.ComponentDef.Props()
	return uprops.(PreviewProps)
}

func (p PreviewProps) EqualsIntf(val interface{}) bool {
	return p == val.(PreviewProps)
}

var _ react.Equals = PreviewProps{}
